name: CI/CD Frontend Docker

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v3
        with:
          context: .                      
          file: ./Dockerfile             
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/frontend-restapi:latest
            ${{ secrets.DOCKER_USER }}/frontend-restapi:${{ github.sha }}
